// Binary Header Field Descriptions based on SEG-Y Rev 1 specification
export const BINARY_HEADER_DESCRIPTIONS: Record<string, { description: string; bytes: string }> = {
    jobId: { description: 'Job identification number', bytes: '1-4' },
    lineKey: { description: 'Line number', bytes: '5-8' },
    reelKey: { description: 'Reel number', bytes: '9-12' },
    tracesPerEnsemble: { description: '# data traces per record', bytes: '13-14' },
    auxTracesPerEnsemble: { description: '# aux traces per record', bytes: '15-16' },
    sampleInterval: { description: 'Sample interval [microseconds] for reel', bytes: '17-18' },
    sampleIntervalOriginal: { description: 'Sample interval [microseconds] for field', bytes: '19-20' },
    samplesPerTrace: { description: 'Number samples per data trace for reel', bytes: '21-22' },
    samplesPerTraceOriginal: { description: 'Number samples per data trace for field', bytes: '23-24' },
    sampleFormat: { description: 'Data sample format code', bytes: '25-26' },
    ensembleFold: { description: 'CDP fold', bytes: '27-28' },
    traceSorting: { description: 'Trace sorting code', bytes: '29-30' },
    verticalSumCode: { description: 'Vertical sum code', bytes: '31-32' },
    sweepFrequencyStart: { description: 'Sweep frequency at start', bytes: '33-34' },
    sweepFrequencyEnd: { description: 'Sweep frequency at end', bytes: '35-36' },
    sweepLength: { description: 'Sweep length [milliseconds]', bytes: '37-38' },
    sweepType: { description: 'Sweep type code', bytes: '39-40' },
    traceNumberSweepChannel: { description: 'Trace number of sweep channel', bytes: '41-42' },
    sweepTraceTaperLengthStart: { description: 'Sweep trace taper length at start [ms]', bytes: '43-44' },
    sweepTraceTaperLengthEnd: { description: 'Sweep trace taper length at end [ms]', bytes: '45-46' },
    taperType: { description: 'Taper type', bytes: '47-48' },
    correlatedDataTraces: { description: 'Correlated data traces', bytes: '49-50' },
    binaryGain: { description: 'Binary gain recovered', bytes: '51-52' },
    amplitudeRecoveryMethod: { description: 'Amplitude recovery method', bytes: '53-54' },
    measurementSystem: { description: 'Measurement system (1-m / 2-feet)', bytes: '55-56' },
    impulseSignalPolarity: { description: 'Impulse signal', bytes: '57-58' },
    vibratoryPolarityCode: { description: 'Vibratory polarity code', bytes: '59-60' },
};
